### ISSUE TITLE
sahplanes array seems unnecessary?

### ISSUE THREAD

**Issue by Vykaash** [gkjohnson/three-mesh-bvh#122]
There is a section of code in BVHConstructionContext constructor where a 3xN array is constructed to hold objects representing a piece of information from bounds and index. However, the area of code inside getOptimalSplit that uses this is commented out, so it seems unnecessary to have an entire new array when we can just index into bounds directly when needed. 

In BVHConstructionContext constructor:
```js
// SAH Initialization - not needed?

this.sahplanes = null;
if ( options.strategy === SAH ) {
    const triCount = geo.index.count / 3;
    this.sahplanes = [ new Array( triCount ), new Array( triCount ), new Array( triCount ) ];
    for ( let tri = 0; tri < triCount; tri ++ ) {
        for ( let el = 0; el < 3; el ++ ) {
            this.sahplanes[ el ][ tri ] = { p: this.bounds[ tri * 6 + el * 2 ], tri };
        }
    }
}
```

Later in getOptimalSplit
```js
// Get the precalculated planes based for the triangles we're
// testing here
const filteredLists = [[], [], []];
for (let i = offset, end = offset + count; i < end; i++) {
    for (let v = 0; v < 3; v++) {
        // original
        filteredLists[v].push(this.sahplanes[v][i];
        // could be - filteredLists[v].push(this.bounds[i * 6 + v * 2]);
    }
}
```

several lines down the commented out code begins
```js
/*
// compute the other bounding planes for the box
// if only the current triangles are considered to
// be in the box
// This is really slow and probably not really worth it
```

Of course, if there are other plans for this array than it would make sense to keep it.

**Comment by gkjohnson** [comment]
Hey! Thanks for submitting the issue -- I had to remind myself of that code path a bit more but it does look like `sahPlanes` _is_ used in `getOptimalSplit`:

- The split planes for the the triangle in the parent bounds are tracked [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L255) in the variable `filteredLists`.
- Which is then referenced in the loop below [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L281) with the variable `planes`.
- Which is then stored as `pinfo` in the nested loop [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L289) and that's ultimately used to calculate the cost based on surface area [here](https://github.com/gkjohnson/three-mesh-bvh/blob/master/src/BVHConstructionContext.js#L349).

There is quite a bit of commented out code there but that's for computing the _optimal_ bounds (and therefore lowest cost given the heuristic) for the set of triangles on the left and right including the axes that are not being used to split the parent bounds.

Looking at that SAH branch I think it's pretty clear that there are some improvements to be made and the variable names and comments are not as descriptive as they could be. I haven't been using the SAH strategy in my work because of the high overhead to bounds generation but if you're interested in using it I'd be happy to help put some time into improving it!

Can I ask what you're using the library for? I'm always interested to here how projects are being used.

Thanks again!

**Comment by Go4thNDie** [comment]
Thanks for the quick response!

As I understand it, data in sahplanes array are objects defined as 
`{ p: this.bounds[ tri * 6 + el * 2 ], tri }`

Looking at getOptimalSplit, only the p value is currently used, making sahplanes an array containing the same information as bounds. I was thinking filteredLists could be built like this
`filteredLists[v].push(this.bounds[i * 6 + v * 2]);`

This would mean we can remove sahplanes altogether, saving on some memory for having to store the same information twice.

I'm currently building a viewer for CAD models (STP, IFC etc), and since my scenes are mostly static and filled with complex shapes I became interested in building BVH using SAH to improve ray casting speed. I stumbled upon a stack overflow question where you had linked your project and was impressed by the results so I figured I would dabble in the code and learn.

**Comment by gkjohnson** [comment]
> Looking at getOptimalSplit, only the p value is currently used, making sahplanes an array containing the same information as bounds. I was thinking filteredLists could be built like this
> `filteredLists[v].push(this.bounds[i * 6 + v * 2]);`

At first glance this seems like it would be correct but I'd have to dig into it a bit more. If you're interested in helping to improve that part of the code I'm definitely supportive! If the SAH strategy is the one you're interested in then maybe it makes sense to try to update the optimal bounding box split computation (the commented out code) -- I'm really not even sure if it still works because it's been around for so long. Maybe it warrants a separate strategy type like `CHEAP_SAH` vs `OPTIMAL_SAH` or something if the performance is still actually so significantly slower but that should be tested, first.

> This would mean we can remove sahplanes altogether, saving on some memory for having to store the same information twice.

If you're interested in improving general memory consumption then maybe take a look at the second bullet point in #42 which basically just suggests storing all the bounds and triangle data in a single flat array rather than a recursive object structure which would remove some runtime overhead, as well. I haven't had the need or the time to investigate this but I think it would be a big improvement to the project.

Depending on your application you could also look into serializing the tree into a separate file that could be loaded at run time to avoid the tree construction all together. The above suggestion would make that a lot simpler.
