### ISSUE TITLE
Failed to load glTF model Error: MeshBVH: InterleavedBufferAttribute is not supported for the position attribute.

### ISSUE THREAD

**Issue by arpu** [gkjohnson/three-mesh-bvh#146]
Hey, 
testing the fast BVH raycaster with a gltf Model optimizes with https://github.com/zeux/meshoptimizer from @zeux

do i need to tranform the InterleavedBufferAttribute  to BufferAttribute?

**Comment by gkjohnson** [comment]
Hey @arpu! Yeah unfortunately InterleavedBufferAttributes are not supported in either the index or position attribute as listed in the [gotchas](https://github.com/gkjohnson/three-mesh-bvh#gotchas) section. This is because we use direct array access to the buffers when building the bvh for the sake of speed.

You'll have to deinterleave the buffer attribute into a regular BufferAttribute in order to create a MeshBVH. Looking over the code briefly it _might_ be possible to adjust the library so interleaved buffers are supported for position but not for index because the index array is sorted to represent the bvh. I won't have time to look into that for a bit, though.
