### ISSUE TITLE
Indices does not return correct position

### ISSUE THREAD

**Issue by ibrahimunal** [gkjohnson/three-mesh-bvh#225]
I might have misunderstood the concept but as far as I can get , in the collectTriangle.js file the parameter a ,b and c give us the indexes of the vertexes. (indices)

```
	( tri, a, b, c, contained ) => {
		if ( contained || tri.intersectsSphere( sphere ) ) {
		indices.push( a, b, c );
		}
		return false;
	}
```
and by using those indexes I get their positions of those vertexes and create a new Vector3 by using this code block

```
vector3dA.fromBufferAttribute(targetMesh.geometry.attributes.position,a);
vector3dB.fromBufferAttribute(targetMesh.geometry.attributes.position,b); 
vector3dC.fromBufferAttribute(targetMesh.geometry.attributes.position,c);

```
So if I select 2 face which are adjacent to each other,  they must have 2 common vertex because they share a edge. But this is what I get when I select two faces which have a common edge. None of their vertexes are the same 

![image](https://user-images.githubusercontent.com/36535542/110637914-f8a0f700-81be-11eb-99bd-1b20038ec9bf.png)

Also another thing I realize was that common vertexes has unique indexes. Suppose two triangle intersect with each other and possible indices they can get is {0 , 1 , 2 , 3 } but in this format it is { 0 , 1  ,2 ,3 ,4 ,5} (in its geometry.index buffer attributes). 

As I mentioned , I might be wrong since im new to three js but I'd be so glad if i get any help

**Comment by gkjohnson** [comment]
Hi @ibrahimunal! Yes the docs could probably be more clear on this topic but the indices passed into the function are indices into the index attributes, which you can see used [here in the collectTriangles.js files](https://github.com/gkjohnson/three-mesh-bvh/blob/84e1dcadece0ee13468e2bb7479b2dade6094042/example/collectTriangles.js#L269-L276).

So in order to get the vertex positions of the triangle you must read from the index attribute first:

```js
const indexAttribute = targetMesh.geometry.index;
const positionAttribute = targetMesh.geometry.attributes.position;
vector3dA.fromBufferAttribute(positionAttribute, indexAttribute.getX(a));
vector3dB.fromBufferAttribute(positionAttribute, indexAttribute.getX(b)); 
vector3dC.fromBufferAttribute(positionAttribute, indexAttribute.getX(c));
```

This does mean that `a`, `b`, and `c` will always be sequential and different for every triangle so it's a little redundant. In the next v0.4.0 release I may change the function to provide the _triangle_ index which would change the above code to look like this which will hopefully lead to less confusion:

```js
vector3dA.fromBufferAttribute(positionAttribute, indexAttribute.getX(triIndex * 3));
vector3dB.fromBufferAttribute(positionAttribute, indexAttribute.getX(triIndex * 3 + 1)); 
vector3dC.fromBufferAttribute(positionAttribute, indexAttribute.getX(triIndex * 3 + 2));
```

If I make the change then I will change the whole function signature so a deprecation warning will be logged if you happen to be using the old version (see #218) and won't break without warning on the subsequent release.

**Comment by ibrahimunal** [comment]
I just realized indexAttribute function after I created the post. I literally did the same thing and it worked as it suppose to be. Greatfull  for your response btw this makes more sense now !!

**Comment by gkjohnson** [comment]
Glad you got it working!
