### ISSUE TITLE
How to include as standalone file without node.js, etc?

### ISSUE THREAD

**Issue by LukePH** [gkjohnson/three-mesh-bvh#233]
This library looks great. I'm working with Three.js and just straight apache right now and having trouble including this in my project.

I might be missing something very obvious as I'm inexperienced with modern javascript toolkits but is there a way for me to build a single standalone js file like Three.js, etc have? 

I see someone ask that before here, but they closed their issue:
https://github.com/gkjohnson/three-mesh-bvh/issues/143

I see the umd/index.js build file, but doesn't seem like it's straight forward to include directly.

**Comment by gkjohnson** [comment]
If you're using the classic JS script includes then the `umd/index.js` is what you're looking for. You'll want to include that file after three.js has been included on the page:

```html
<script src="./path/to/three.js"></script>
<script src="./path/to/three-mesh-bvh/umd/index.js"></script>
```

Then using the UMD build is outlined a bit in the README:

```js
// Or UMD
const { MeshBVH, acceleratedRaycast } = window.MeshBVHLib;
```

**Comment by LukePH** [comment]
I am using ES6 modules imports so I was tunnel visioning on the 'Import via ES6 modules' part of the docs.

Thank you, I knew the window.MeshBVHLib wouldn't work by it's self, but didn't realise I just needed a classic script tag with that, as I didn't really know anything about UMD packages.

This is what I have now:

```
<script src="/libraries/three/three.js"></script>
<script src="/libraries/MeshBVH_umd.js"></script>

<script type="module">
'use strict';

//import * as THREE from '/libraries/three/three.module.js';  //Had this before
import { TDSLoader } from '/libraries/three/jsm/loaders/TDSLoader.js';
import { FBXLoader } from '/libraries/three/jsm/loaders/FBXLoader.js';
import { SkeletonUtils } from '/libraries/three/jsm/utils/SkeletonUtils.js';
import Stats from '/libraries/three/jsm/libs/stats.module.js';
...

const { MeshBVH, computeBoundsTree, disposeBoundsTree, acceleratedRaycast } = window.MeshBVHLib;

...

</script>
```


And it works!, but it would be nice to keep the Three.js module import I had before, and include three-mesh-bvh via import like everything else. But I could put up with doing it this way.

**Comment by gkjohnson** [comment]
Manually including libraries with dependencies that use modules is a complicated use case in Javascript right now. Packages use "bare module imports" because you can't predict the users folder structure and where the common version of three.js (in this case) should live. "Import Maps" may make this easier but they're not widely supported, yet.

This library generally doesn't use anything aside from bare module imports that requires bundling so one option is to just copy the source and modify all instances of `import ... from 'three'` to point to your copy of three.js. Or you can modify the rollup script to generate an es6 module file rather than UMD that will only have one instance of `import ... from 'three'` to modify.

**Comment by LukePH** [comment]
Yeah looks like all the loaders, etc include the 'three.module.js' file, so I cannot avoid importing it. So yeah using the <script> tag just included 2 three libraries. Explains why the documented computeBoundsTree prototype lines didn't work for me without some extra monkeypatching hacks.

Yeah does seems like module dependencies can be a bit of a mess with manual imports, maybe a es6 module that just does a relative import of the three module (like the included loaders and utils in three) and requires placement in the same folder as three would work for most people?

For now it seems I'm out of luck with this current library and my setup? I'll look into the rollup script changes later, but I don't know anything about that build tool.

**Comment by gkjohnson** [comment]
> maybe a es6 module that just does a relative import of the three module (like the included loaders and utils in three) and requires placement in the same folder as three would work for most people?

I think this use case is relatively uncommon and peoples server folder setups are always unpredictable so I don't think it's viable to do that. This is a limitation of the current browser spec and there's no great way to distribute proper browser modules that have dependencies at the moment.

I may update the build process to produce an additional single js module file for this use case but you will still have to modify the import to point to your local version of three. Until I have a chance to do that you should be able to change [this line](https://github.com/gkjohnson/three-mesh-bvh/blob/2ac3c87cf2759accdc9cfe04e2ae9098ecb5d10d/rollup.config.js#L10) to `format: 'es'` then run `npm install` then `npm run build` and it should pop out a single es6 module file rather than a UMD file that's easier to modify.
