### ISSUE TITLE
characterMovement.js sliding down crooked floor

### ISSUE THREAD

**Issue by vin-ni** [gkjohnson/three-mesh-bvh#247]
Hi,
I have an issue I can't find a fix for. Once the player is on a slanted floor, the character slowly slides down that angle. Is there any way to prevent that? I think it's due to some vector calculation.

For example when I am on the stairs, it slides. Here's a [screencast](https://www.dropbox.com/s/sypsysjwq7xuk4e/sliding%20three-mesh-bvh.mp4?dl=0).

Thank you!

**Comment by gkjohnson** [comment]
Hello! The character movement demo is a quick example to show how the project can be used but it will have to be adjusted depending on what types of movement and interaction you want for your project. The capsule slides down the stairs because the rounded bottom of capsule is sitting on the corner of the stair and is being pushed by both the horizontal and vertical triangles of the stair. It may be possible to adjust the capsule physics to prioritize adjusting relative to horizontal triangles first so the movements due to vertical triangles are minimized but I haven't given that too much thought.

You can also take a look at [this section of the code](https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/characterMovement.js#L416-L427) to adjust when gravity is being applied which is currently based on the direction the capsule has been "pushed" over the last physics step. Lastly because this issue is specifically caused by the stair shape in this case you should be able make a proxy mesh just for physics that just uses a smooth ramp to walk up which may alleviate the issue, as well.

**Comment by vin-ni** [comment]
Hello @gkjohnson ,
sorry for the late reply, I was a bit busy these days. Thanks for the info.

I tried replacing the capsule with a cube, but had the same result of it slowly "drifting" down a convex shape. I will try to play around with the part that you linked.

It might be too much to ask, but would you mind adding some comments to the `updatePlayer` from around [here](https://github.com/gkjohnson/three-mesh-bvh/blob/e59994854ddbf6a4ccdf88f2947234e65f80a1e0/example/characterMovement.js#L367). I have a bit difficulties understading your approach and calculations.

Thanks!
Vinzenz

**Comment by gkjohnson** [comment]
> I tried replacing the capsule with a cube, but had the same result of it slowly "drifting" down a convex shape. I will try to play around with the part that you linked.

Just replacing the visuals of the player with a cube is not enough -- updating the player movement uses a mathematical representation of a capsule rather than the geometry of the player. Can you elaborate on the convex shape you're intersecting against? The `updatePlayer` function checks against all triangles that might intersect with the capsule so small or hidden triangles can have an unexpected impact on the player movement. The demo uses the fully detailed model for collision but there are cases where the small lips or triangles used to represent cracks between tiles or walls cause issues. Using a more simplified model is one way to alleviate these kinds of issues. A simple flat slope made from a box (that is shallow enough) shouldn't cause the player to slide down it. The sliding in the current demo is due to the stairs as far as I can tell.

> It might be too much to ask, but would you mind adding some comments to the `updatePlayer`

Sure! I've added a [few more comments](https://github.com/gkjohnson/three-mesh-bvh/blob/9c42a4e406ddfac49397e2cff5813cd2d1aef7d4/example/characterMovement.js#L364-L447) to the example -- let me know if that's more clear. I'm always happy to answer questions and give advice where I can I just don't always have as much bandwidth as I'd like to dig into all these issues. Hopefully one of these things is helpful.

And sorry about pre-emptively closing the issue I've had a number of cases where people make new issues and never respond again so I've gotten in the habit of closing some of them after a week or so no response. If you want we can open this one back up or of course you can always open a new issue if you run into something new!

**Comment by gkjohnson** [comment]
> you should be able make a proxy mesh just for physics that just uses a smooth ramp to walk up which may alleviate the issue, as well.

Thinking about this a bit more I'm actually no longer confident this would address the issue. I'll have to find time to dig into it a bit more and figure out what can be don about it. I've created a new issue (#251) to look into it.

**Comment by vin-ni** [comment]
Thank you so much Garret!
