### ISSUE TITLE
Question: Possible to use GeometryCompressionUtils with three-mesh-bvh?

### ISSUE THREAD

**Issue by vegarringdal** [gkjohnson/three-mesh-bvh#249]
Possible to use GeometryCompressionUtils with three-mesh-bvh?

https://threejs.org/examples/webgl_buffergeometry_compression

Tried to run `GeometryCompressionUtils.compressPositions(mesh);` before and after `mesh.geometry.computeBoundsTree();`
Hoping its something simple I can do to get it to work, would be awesome to have good raycaster and use less memory 

Amazing work with the `three-mesh-bvh` btw, its like magic 😄 (atleast for me :joy:)

**Comment by gkjohnson** [comment]
Hello! There's no support for that kind of compressions in this library and I don't believe even three.js' built-in raycaster will work with it because of the way the vertex positions are represented and unpacked in a shader. If the compression utils worked by quantizing the position buffer and then scaling the mesh appropriately then both raycasting systems would work -- eg if a geometry spans from `[ -1, 1 ]` and it's quantized into 8 bit values in the range `[ -127, 127 ]` with the mesh scaled on all dimensions by `1 / 127` then the mesh should look correct, require no shader changes (for positions), and all transformed vertex positions would be correct, and this bvh package and three.js' raycasting would work. Of course that requires changes from the compression utils in three, though.

> Amazing work with the three-mesh-bvh btw, its like magic 😄

Glad to hear it! If you have any work you can share that's benefited from this project I always like to see it.
