### ISSUE TITLE
edgeProjection.js export drawing

### ISSUE THREAD

**Issue by yepher** [gkjohnson/three-mesh-bvh#461]
edgeProjection.html is a fantastic example, but there is no way to export a vector version of the 2D drawing 

**Describe the solution you'd like**

How would one write some code to export the 2D drawing as a `dxf` file?

**Comment by gkjohnson** [comment]
The demos are designed to show how to use the BVH structure for a variety of use cases including fast edge projection and I feel exporting the edges to a file format is outside the scope of the example. I'm unfamiliar with DXF files but you should be able to iterate over the result of "finalEdges" to write some kind of exporter with the result of the edge projection.

**Comment by yepher** [comment]
finalEdges was just the tip I needed. Thanks.

**Comment by yepher** [comment]
@gkjohnson I see the values in `finalEdges` are start.x,y,z and end.x,y,z

When use the attached `Box.glb` and iterate over finalEdges.glb I get values that do not seem to represent a square like I expect. This is how I am rendering the line segments:

```
for ( let i = 0, l = edges.length; i < l; i ++ ) {

		const line = edges[ i ];
		svg += '<line ' +
			'x1="' + line[ 0 ].toFixed( 2 ) + '" ' +
			'y1="' + line[ 1 ].toFixed( 2 ) + '" ' +
			'x2="' + line[ 3 ].toFixed( 2 ) + '" ' +
			'y2="' + line[ 4 ].toFixed( 2 ) + '" ' +
			'stroke="black" />\n';
}
```

I thought the final edges would have been the drawing at the bottom of the screen. But I must have a fundamental misunderstanding of what that data is. If that is not correct, do you know an easy way to get the array of lines that are drawn at the bottom?

I was expecting the SVG to produce the square shown in this image
<img width="315" alt="expected" src="https://user-images.githubusercontent.com/1359331/189253370-c51e5a9d-ce67-409b-9e9e-ff544218ab88.png">



[edges.svg.zip](https://github.com/gkjohnson/three-mesh-bvh/files/9531608/edges.svg.zip)

[Box.glb.zip](https://github.com/gkjohnson/three-mesh-bvh/files/9531606/Box.glb.zip)

**Comment by yepher** [comment]
Looking at this more, I think I want line indexes 0,2 and 3,5. But I still have not worked out why the drawing is so small.

**Comment by yepher** [comment]
Success!!! But I am not quite sure how to get the `finalEdges` to be the same scale as the original. My goal is to be able to measure the resulting drawing to find the sizes of various elements. 

<img width="1156" alt="edges" src="https://user-images.githubusercontent.com/1359331/189261900-202fe16c-605f-4ffa-9539-8e118e3889bd.png">

**Comment by gkjohnson** [comment]
> Success!!! But I am not quite sure how to get the finalEdges to be the same scale as the original. My goal is to be able to measure the resulting drawing to find the sizes of various elements.

Nice! Yes the edge pairs stored in "finalEdges" are in 3D and will be projected along Y - so the X and Z values are the ones you're going to want to use for export.

In terms of scale the edges will be in world scale so they should already be in the appropriate scale. One thing to keep in mind, though, is the assumed "base units" of any given rendering environment or format. Three.js more or less assumes that 1 unit is 1 meter. Depending on the environment, though, "1 unit" maybe assumed to be 1 cm or otherwise. So it's something to keep in mind - you may need to apply some scale factor on the way out. One quick thing to test is that the cube should be 1 unit by 1 unit across. If it's not then maybe we can look into what's going on there.

Also for a little more context - that demo was made for [IFC JS project](https://ifcjs.github.io/info/) ([twitter](https://twitter.com/ifc_js)) so they could generate top down projections and ultimately export DXF files for BIM models. So they may be worth talking to if that use case sounds related.

**Comment by YingjuHan** [comment]
> Success!!! But I am not quite sure how to get the to be the same scale as the original. My goal is to be able to measure the resulting drawing to find the sizes of various elements.`finalEdges`
> 
> <img alt="edges" width="1156" src="https://user-images.githubusercontent.com/1359331/189261900-202fe16c-605f-4ffa-9539-8e118e3889bd.png">

Congratulations! I had this problem a long time ago and was stuck, can you provide a way to implement it? Thank you.
