### ISSUE TITLE
A question about mesh selection

### ISSUE THREAD

**Issue by YingjuHan** [gkjohnson/three-mesh-bvh#490]
I have a question about the sample code of grid selection and want to get your answer: why is there a judgment on the intersection of lines and lines at the end of the judgment of triangle intersection? After I removed this piece of code, I found that the result seems to be nothing changes.
Hope to get your reply and answer, thank you!

**code:** 
[https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/selection.js](url)

``` javascript
// get the lines for the triangle
const lines = [
	boxLines[ 0 ],
	boxLines[ 1 ],
	boxLines[ 2 ],
];

lines[ 0 ].start.copy( tri.a );
lines[ 0 ].end.copy( tri.b );

lines[ 1 ].start.copy( tri.b );
lines[ 1 ].end.copy( tri.c );

lines[ 2 ].start.copy( tri.c );
lines[ 2 ].end.copy( tri.a );

for ( let i = 0; i < 3; i ++ ) {

	const l = lines[ i ];
	for ( let s = 0, sl = segmentsToCheck.length; s < sl; s ++ ) {

		if ( lineCrossesLine( l, segmentsToCheck[ s ] ) ) {

			indices.push( a, b, c );
			return params.selectModel;

		}

	}

}
```

**Comment by gkjohnson** [comment]
[This section](https://github.com/gkjohnson/three-mesh-bvh/blob/1f39844ee7b73d14a4fc8594c2b98686c72846e6/example/selection.js#L647-L668) checks if any of the triangle vertices are within the selection region which would mean that the triangle would be selected:

https://github.com/gkjohnson/three-mesh-bvh/blob/1f39844ee7b73d14a4fc8594c2b98686c72846e6/example/selection.js#L647-L668

However this is not enough to determine if the selection intersects the triangle. Consider the case where the lasso is such that it contains no vertices but loops over one of the edges. The [section you're referring to](https://github.com/gkjohnson/three-mesh-bvh/blob/1f39844ee7b73d14a4fc8594c2b98686c72846e6/example/selection.js#L670-L704) checks for that condition:

https://github.com/gkjohnson/three-mesh-bvh/blob/1f39844ee7b73d14a4fc8594c2b98686c72846e6/example/selection.js#L670-L704

Both checks are performed because the first case can be significantly faster than the second and lets us early out if needed.

**Comment by YingjuHan** [comment]
This case was missed by me, thanks for your reply
