### ISSUE TITLE
SDFRaymarch - Read the depth value

### ISSUE THREAD

**Issue by RenaudRohlinger** [gkjohnson/three-mesh-bvh#491]
I'm looking for a way to get the correct depth value of a raymarching result. I will open an issue here as I think it could benefit other developers too.

I made an example with a post process splitting the screen into 4 sections: 
1 - scene albedo
2 - raymarching albedo
3 - scene depth
4 - raymarching depth (using custom `gl_FragDepth` = `length(point.xyz)`)

https://codesandbox.io/s/romantic-sunset-uqhc13?file=/src/RayMarchSDFMayerial.js
![image](https://user-images.githubusercontent.com/15867665/202856734-64af1688-daa9-4dd8-bc99-4dd281e5e4b0.png)

**Comment by gkjohnson** [comment]
Hmm - I'm not able to see the raymarch depth buffer on my machine. Is there something I need to enable?

<img width="719" alt="image" src="https://user-images.githubusercontent.com/734200/202878071-edfbec95-7a34-4a08-98d5-9e85091ac6d5.png">

**Comment by RenaudRohlinger** [comment]
Oh, my bad indeed!

It seems that some GPUs do not like the `texelFetch` syntax. I changed it with a basic `texture()`

`readDepthFrag(texelFetch(sceneDepth, fCoord, 0).x` => `texture(sceneDepth, vUv).x`

It should be fixed @gkjohnson 👍

**Comment by CodyJasonBennett** [comment]
Looks like I get a correct result with `viewZToPerspectiveDepth`, initializing `fragCoordZ = -1`. Taking note of the math linked from https://github.com/mrdoob/three.js/blob/bb23058464420d8fd510337ff400182ba662e8dd/src/renderers/shaders/ShaderChunk/packing.glsl.js#L54.

```glsl
float cameraNear = 0.1;
float cameraFar = 5.0;

gl_FragDepth = viewZToPerspectiveDepth(-(fragCoordZ / gl_FragCoord.w), cameraNear, cameraFar);
```

![image](https://user-images.githubusercontent.com/23324155/202913402-a33b4f22-bbe8-4a2a-bd42-4bac988d7b9e.png)

**Comment by gkjohnson** [comment]
Thanks @CodyJasonBennett this is great!

A few changes to make still, I think. You shouldn't need to do anything with fragCoord.w since the raymarching is happening in view space (no projection matrix applied) and the w coordinate should be 1.0 anyway since it's just a full screen quad being rendered in that pass.

And I believe the fragCoordZ should be set to `point.z` rather than `length( point.xyz )` since it just needs to test z distance for depth:

```hlsl
float fragCoordZ = - 1.0;

// ...

if ( intersectsSurface ) {

  fragCoordZ = point.z;
  // ...

}

// ...

gl_FragDepth = viewZToPerspectiveDepth( - fragCoordZ, cameraNear, cameraFar );
```

The depth visually matches a lot more precisely after these changes though more testing should still be done to make sure the type of shifting you originally showed me is addressed @RenaudRohlinger.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/734200/202950946-ffee3879-6abd-4fc2-98cf-c6a19b00bbfa.png">

For performance reasons in the raymarch loop, though, I would transform the scene depth from the existing depth buffer beforehand to check in the for loop.

**Comment by CodyJasonBennett** [comment]
Awesome, I had to set `fragCoordZ = -point.z`, but it works nicely.

**Comment by gkjohnson** [comment]
> Awesome, I had to set fragCoordZ = -point.z, but it works nicely.

Oops - you're right. I'd inadvertently been taking the absolute value of point.z. I've updated my notes above to specify your change. Thanks!

**Comment by RenaudRohlinger** [comment]
Awesome! Thank you so much for this guys, it's working perfectly 😊

**Comment by gkjohnson** [comment]
> Awesome! Thank you so much for this guys, it's working perfectly 😊

Twitter pics please! 🙏
