### ISSUE TITLE
The shapecast function in Mesh Selection

### ISSUE THREAD

**Issue by wyq521** [gkjohnson/three-mesh-bvh#516]
Why not check ` sx > maxX && ex > maxX` in intersectsBounds function? I add it and get a wrong result.
![image](https://user-images.githubusercontent.com/37578994/221345487-50410d99-3014-45d2-a3ad-e64542f57c50.png)
https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/selection.js

**Comment by wyq521** [comment]
I want to know more about function pointRayCrossesLine in selection.js .How do `prevDirection` and `thisDirection` work?

**Comment by gkjohnson** [comment]
> Why not check  sx > maxX && ex > maxX in intersectsBounds function?

The ray-crossing algorithm requires checking only one ray and whether or not it has cross an odd or even number of crossings to determine containment. Assuming the ray being used is the one directly to the right / +X direction that section of code is filtering the set of segments to check to improve performance. Since the ray is only being cast to the right you want to ensure only rays to the right are saved for the check.

> How do prevDirection and thisDirection work?

These variables track the direction of the segment from start direction to end direction (up or down) as a bool (false for up, true for down). This is used to only check the edges of the lasso segments when it changes directions since connected segments will always overlap at one point. TBH I'm not sure why it was important to check only when the direction changes. It's possible that the function could be adjusted to account for the overlap by just ignore the start or end point but it's been awhile since I've worked on that example.

**Comment by wyq521** [comment]
Thanks for your reply.
