### ISSUE TITLE
bvh shapecastTraverse

### ISSUE THREAD

**Issue by blueRaining** [gkjohnson/three-mesh-bvh#521]
![image](https://user-images.githubusercontent.com/41565968/232181673-e78a250c-5e14-4bdd-bb4a-23fce514f3d1.png)

nodeIndexByteOffset is byte offset and nodeIndex32 is the index of the _uint32Array,why they can add together?

**Comment by gkjohnson** [comment]
It's explained slightly better in the `refit` function here: https://github.com/gkjohnson/three-mesh-bvh/blob/a1665f35bc3b17f6832deb4aa9a7e422695dceec/src/core/MeshBVH.js#L272-L273

The argument passed into the function is just a unique identifier for the bvh node which can be passed into the `refit` function. Because there are separate BVH roots generated for each geometry "group" range the group byte offset is added to the 32 bit node index which ensure uniqueness among groups.

It might be worth encapsulating the add operation into a function or adding a comment in the shapecast function for clarity if you'd like to make a PR.
