### ISSUE TITLE
Rotation of MeshBVH + update Mesh with Physics

### ISSUE THREAD

**Issue by Etidou** [gkjohnson/three-mesh-bvh#610]
Hey,

First of all, thank you for this impressive library!

I'm having a bit of trouble getting the collider to rotate and my physics object to react to motion!  

I'm using your ["Sphere Physics collision" example](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/physics.html).

My goal is to rotate the island and roll the sphere down or up depending on the rotation and potential collision that occurs.

`mergedGeometry.boundsTree = new MeshBVH( mergedGeometry ) ;

collider = new THREE.Mesh( mergedGeometry ) ;`

I rotate the collider in the update function (it rotate but meshes with physics (sphere) don't move).

I also see that mergeGeometry (the meshBVH instance) only has access to the RotateX, RotateY, RotateZ functions to apply the rotation.

So there's a way to rotate the collider and update MeshBVH easily.

Here's a [Zip](https://github.com/gkjohnson/three-mesh-bvh/files/13886182/BVH-Test-dev.zip) of my current project and the [live version](https://three-mesh-bvh-rotation-test.netlify.app/) of my current state

**Comment by Etidou** [comment]
I'm dumb, in my update function if I add:
```
staticGenerator.generate( mergedGeometry );
mergedGeometry.boundsTree.refit();
```
It seems to be work
[Project Files](https://github.com/gkjohnson/three-mesh-bvh/files/13886763/BVH-Test-dev.2.zip)

@gkjohnson Is this the best solution ?

**Comment by gkjohnson** [comment]
Hello! In order to perform physics with moving colliders you have to transform the objects you want to collide into the frame of the collider - ie the the frame of the mesh you're displaying.

> (The line staticGenerator.generate( mergedGeometry ); seems to dissociate the environment and the collider, but without it physics doesn't work)
> @gkjohnson Is this the best solution and do you have a solution for the dissociation?

StaticGeometryGenerator produces a geometry, not a mesh, so there is no transformation information associated with it. Keep in mind that three-mesh-bvh is not a physics library - though of course you can perform physics related calculations using it as the demo shows - so Managing transforms and relationships between colliders is something you'll have to manage yourself.

**Comment by Etidou** [comment]
Thanks for your fast Answer !

So if I understand correctly, if I want to update the bvh correctly, I have to give it a new matrix after it has changed its rotation?

And also refit, and static generator generation in my case isn't the most efficient way to do it and besides it's a bit pointless.

**Comment by gkjohnson** [comment]
Once the BVH is created there should no need to rebuild it or modify it since the geometry is not changing.

> So if I understand correctly, if I want to update correctly my spheres, I have to update them with new matrix after the environnement (collider) has changed its rotation?

You need to perform the collision checks in the _local frame of the mesh_. This means you need to transform the balls positions into the local frame of the visual mesh. You can do this using the inverse of the models `matrixWorld` function. You'll need to transform the sphere positions back afterward so they are back in the original world frame. Ie see here in the triangle-painting demo where the brush sphere is transformed into the local frame of the rotating shape:

https://github.com/gkjohnson/three-mesh-bvh/blob/82d7b05be20d722d83a66f6545a5bed4a30e365a/example/collectTriangles.js#L219-L224

**Comment by Etidou** [comment]
Thanks for your help, I understand better!

**Comment by Etidou** [comment]
Thanks for your help, I understand better!

**Comment by Etidou** [comment]
@gkjohnson I still not understanding well something 

When I try your solution, my sphere has no center but has an object called collider which contains the center and radius, but when I give them a new matrix based on the collider (same result with the environment model matrix) the sphere is static and resets its position.


Here is my Update Function call on the render Function
```
function update( delta ) {
	if ( collider ) {
		const steps = params.physicsSteps;
		for ( let i = 0; i < steps; i ++ ) {
			updateSphereCollisions( delta / steps );
		}
      if(xMouse && loaded) {
          const mappedX = map(xMouse, 0, window.innerWidth, -1, 1);
          const mappedY = map(yMouse, 0, window.innerHeight, -1, 1);
    
          collider.rotation.set(MathUtils.degToRad(mappedX * 15), 0, MathUtils.degToRad(mappedY * 15))
          visualizer.rotation.copy(collider.rotation)
          environment.rotation.copy(collider.rotation)
    
          const inverseMatrix = new THREE.Matrix4(); 
          inverseMatrix.copy( collider.matrixWorld ).invert(); 
         
          for(let i = 0; i < spheres.length; i++) {
            // Spheres the Array containing all my Sphere
            // Spheres[i] doesn't existe its remplaced by Spheres[i].collider
            // Spheres stop moving
            spheres[i].collider.center.copy( collider.position ).applyMatrix4( inverseMatrix ); 
            spheres[i].radius = 0.5; 
            console.log(spheres[0])
          }
      }
  }
}
```
Do I have to create a temporary sphere during the update and retrieve their position to associate it with my spheres?

[My js File](https://github.com/gkjohnson/three-mesh-bvh/files/13901280/main.js.zip)
(my live version is still up also)

**Comment by gkjohnson** [comment]
The sphere positions only need to be transformed into the collider frame for the sake of detecting collisions. Any forces, position shifting, and transform tracking should be done in the global frame.

1. update collider transformation
1. transform sphere into collider frame
1. detect collisions, new sphere position due to collision
1. transform new sphere position, forces, etc back into world space
1. apply forces, velocity changes, etc

> Collider Position is never changing so that kinda the problem, his matrixWorld change

You need to call "updateMatrixWorld" after modifying the local variable fields. I recommend reading up a bit more on how the matrix transformations are managed and updated in three.js.

**Comment by Etidou** [comment]
Thanks, I'll stop bothering you, I'll try to set it up Thanks again!

**Comment by gkjohnson** [comment]
Please share what you wind up making!
