### ISSUE TITLE
BVH construction doesn't work when geometries have groups

### ISSUE THREAD

**Issue by mqp** [gkjohnson/three-mesh-bvh#66]
Today I learned that three.js `BufferGeometry` can have [`groups`](https://threejs.org/docs/#api/en/core/BufferGeometry.groups), which are ranges of the index that are meant to be drawn with a different material. For example, you can set the first half of the index to be drawn with one material, and the second half to be drawn with another.

This presents a problem for us because if we reorder the index, we are invalidating the group ranges, so the resulting geometry will be drawn with the wrong materials on different parts of the model.

There are maybe three reasonable things we could do to address this:

1. Don't construct BVHs for geometries with groups. Perhaps we could offer functionality to "ungroup" grouped geometries.
2. Add a layer of indirection like our `tris` which we retain in memory permanently, so that we leave the index alone and store ranges of `tris` in our tree nodes.
3. Create one BVH "root" for each group which only stores and reorders indices in that group. That way, we will still scramble up the index, but the integrity of the groups will remain. When we raycast, raycast down all the roots (minding bounding boxes.)

I think solution number 3 sounds pretty easy and has no real downsides (raycasting might be very slightly more expensive, but that was also true for solution 2, and if someone doesn't like that, they can ungroup their geometries), and we should implement it.

**Comment by gkjohnson** [comment]
I forgot about groups -- good catch. A few thoughts:

- If groups overlap / multiple groups render the same triangles will it be possible to achieve 3? Granted I don't know how often this happens in practice.
- If there are a lot of groups and the the triangles they render are not conveniently organized it may lead to poor raycast performance because the bounds trees could overlap significantly. The original Pickle Rick model we looked at and the way it was broken up into 10s of meshes comes to mind.

Option 2 seems like the most fool-proof method. If you just don't set the index of the geometry if there are groups does that suffice? Of course you'll take the hit of storing two index buffers but only when a geometry uses groups.

**Comment by mquander** [comment]
You're right, the possibility of overlapping groups damages idea number 3 (you could still create a separate tree root for each "overlap region", but it's starting to sound a little silly.)

For option number 2, I mostly dislike the prospect of complicating the code with a bunch of "has groups/doesn't have groups" branches. If we can do it without that, I am OK with it. (Although it makes me sad for the Hubs use case, because for us memory consumption is a lot more important than raycasting performance.)

**Comment by gkjohnson** [comment]
I think option 2 can work without any added logic and knowledge of groups in the BVH class:

```js
geometry.boundsTree = new MeshBVH( geometry );
if ( geometry.groups.length === 0 ) {

    geometry.setIndex( geometry.boundsTree.index );

}
```

So the geometry can render with the group-aligned index while the bounds tree will continue to use the one it created. I know #62 changes the tree building process to edit the index array in place but an option could be added to disable that functionality if desired.

> memory efficiency is a lot more important than raycasting performance.

I totally understand. Do you have any sense for how often groups will overlap? Supporting geometry with groups that _don't_ overlap seems easy enough without getting too complicated. Would it suffice to add "range" options to the bvh construction so it will only consider indices relevant to a group?

```js
// if there are groups and groups don't overlap
geometry.boundsTree =
    geometry.groups.map( g => new MeshBVH( geometry, {
        start: g.state,
        count: g.count
    } ) );
```

And then the raycast function would handle multiple BVHs. I think this would work nicely with your "edit geometry index in place" PR, as well.

**Comment by mquander** [comment]
The top snippet is pretty good, although there would still have to be a change in the raycaster so that it knows to use the "BVH index" instead of the index on the geometry object. Unfortunately, it seems true that #62 would make this approach more annoying.

Indeed, the bottom snippet is basically what I was imagining for option 3. Actually, it's not really that much more work if groups overlap, so maybe I still think option 3 is a good idea.

**Comment by mquander** [comment]
That is, I'm suggesting:
```Javascript
let rangeBoundaries = new Set();
for (let group of geometry.groups) {
  rangeBoundaries.add(group.start);
  rangeBoundaries.add(group.start + group.count);
}
let roots = rangeBoundaries.pairs().map((a, b) => { return new MeshBVH(geometry, a, b - a); });
```
