### ISSUE TITLE
please update you clippedEdges example, it doesn't work

### ISSUE THREAD

**Issue by rkaeplive** [gkjohnson/three-mesh-bvh#681]
Hello, am I do something wrong ?

https://github.com/gkjohnson/three-mesh-bvh/blob/master/example/clippedEdges.js

<img width="1377" alt="image" src="https://github.com/gkjohnson/three-mesh-bvh/assets/80881455/561f942a-1c71-4900-ae3e-fd4f99efe5f7">

<img width="1465" alt="image" src="https://github.com/gkjohnson/three-mesh-bvh/assets/80881455/8e36a632-6e1d-4a4e-a0a5-c23bc603df8e">

My example 
[clippingEdges.js.zip](https://github.com/user-attachments/files/16015403/clippingEdges.js.zip)

**Comment by gkjohnson** [comment]
You can see from the live example page that it [does work](https://gkjohnson.github.io/three-mesh-bvh/example/bundle/clippedEdges.html).

Unfortunately I don't have the bandwidth to debug your project and whatever changes may have been made but if you have a more specific question about how the effect works I can try to answer that. Otherwise I recommend asking for help at the three.js forum:

https://discourse.threejs.org/
